export type TIconNames =
  | 'animatedSpinner'
  | 'archive_secondary'
  | 'arrowDown'
  | 'arrowLeft'
  | 'arrowRight'
  | 'arrowUp'
  | 'ask'
  | 'bell_secondary'
  | 'body_check'
  | 'briefcase'
  | 'briefcase_secondary'
  | 'calendar'
  | 'calendarWithCorner'
  | 'cash'
  | 'cash_filled'
  | 'catalog_secondary'
  | 'chat'
  | 'chat_secondary'
  | 'check'
  | 'circle_question_secondary'
  | 'clock'
  | 'controls'
  | 'copy_secondary'
  | 'cross'
  | 'doc_cargo'
  | 'doc_check'
  | 'doc_lines'
  | 'doc_location'
  | 'doc_plus'
  | 'doc_rudder'
  | 'dot'
  | 'download'
  | 'download_secondary'
  | 'download_high'
  | 'drafts'
  | 'edit'
  | 'edit_secondary'
  | 'email'
  | 'eye_closed'
  | 'eye_opened'
  | 'exclamation'
  | 'exclamationTriangle'
  | 'file_alert'
  | 'file_crossout'
  | 'file_default'
  | 'file_default_secondary'
  | 'file_dot'
  | 'file_download'
  | 'file_check'
  | 'file_check_secondary'
  | 'file_info'
  | 'file_minus'
  | 'file_pause'
  | 'file_plus'
  | 'file_question'
  | 'file_x_cross'
  | 'flowStatusOk'
  | 'flowStatusClosed'
  | 'flowStatusWait'
  | 'flowStatusAlert'
  | 'flowStatusPrepare'
  | 'flowStatusStopGrey'
  | 'fns'
  | 'fss'
  | 'headphones_secondary'
  | 'inbox'
  | 'integration_edo_onec'
  | 'key'
  | 'list_secondary'
  | 'load'
  | 'location'
  | 'logout'
  | 'loupe'
  | 'mail'
  | 'mail_secondary'
  | 'odometer_reading'
  | 'ok'
  | 'person'
  | 'paint'
  | 'pfr'
  | 'phone'
  | 'planet'
  | 'plus'
  | 'plus_secondary'
  | 'position'
  | 'print'
  | 'print_secondary'
  | 'qr'
  | 'question_secondary'
  | 'refresh'
  | 'rosstat'
  | 'services_ofd'
  | 'services_edo'
  | 'services_go'
  | 'services_epd'
  | 'services_mchd'
  | 'sfr'
  | 'smartphone'
  | 'tech_condition'
  | 'triangle_alert'
  | 'urn'
  | 'urn_secondary'
  | 'user_secondary'
  | 'users_secondary'
  | 'x_cross_secondary';

export type TProductNames =
  | 'default'
  | 'ofd'
  | 'edo'
  | 'gosotchet'
  | 'td'
  | 'marking'
  | 'check-index'
  | 'big-data'
  | 'arenda'
  | 'integrations'
  | 'onec'
  | 'mchd';

export type TThemeNames =
  | 'grey'
  | 'common'
  | 'info'
  | 'success'
  | 'warning'
  | 'error'
  | 'white';

export type TStyleTypes =
  | 'primary'
  | 'secondary'
  | 'default'
  | 'borderless'
  | 'invisible'
  | 'aside-primary'
  | 'aside-secondary';

export type TComponentTypes = 'button' | 'input';

export type TIconPosition = 'left' | 'right';

export type TInputFieldTypes =
  | 'default'
  | 'email'
  | 'inn'
  | 'innPerson'
  | 'kpp'
  | 'innOrganisation'
  | 'innOrg'
  | 'snils'
  | 'ogrn'
  | 'ogrnIp'
  | 'vehicleNumber'
  | 'phone'
  | 'passport'
  | 'passportCode'
  | 'date'
  | 'guid';

export type TUploadFileTypes = 'base64' | 'file';

export type TPopperPlacements =
  | 'top-start'
  | 'top'
  | 'top-end'
  | 'right-start'
  | 'right'
  | 'right-end'
  | 'bottom-end'
  | 'bottom'
  | 'bottom-start'
  | 'left-end'
  | 'left'
  | 'left-start';
